# JVM ayarları — AGP 8.5 için JDK 17 gerekir.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

# AndroidX zorunlu (Glance/WorkManager/DataStore hepsi AndroidX).
android.useAndroidX=true
android.nonTransitiveRClass=true

# Kotlin resmi kod stili.
kotlin.code.style=official
